# Save this as .github/workflows/build-exe.yml in your GitHub repo
name: Build Windows EXE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name "PDF_Analyzer" pdf_analyzer_gui.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: PDF_Analyzer_Windows
          path: dist/PDF_Analyzer.exe
